import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bot, BrainCircuit, CheckCircle2, Clock3, Database, FileSpreadsheet, Filter, Gauge, Landmark, LockKeyhole, MessageSquareText, Play, RefreshCcw, Search, ShieldCheck, Sparkles, Table2, UploadCloud, WalletCards, Workflow, XCircle } from 'lucide-react';
import { motion } from 'framer-motion';

type Page = 'overview' | 'agents' | 'bank' | 'reconciliation' | 'bi' | 'audit' | 'settings';
type AgentStatus = 'Ready' | 'Scheduled' | 'Demo Mode' | 'Needs Connection' | 'Paused';
type MatchStatus = 'Matched' | 'Probable Match' | 'Review Required' | 'Unmatched Credit' | 'Duplicate';
type Agent = { id: string; name: string; purpose: string; mode: 'Headless' | 'Interactive'; model: string; mcp: string[]; schedule: string; status: AgentStatus; icon: typeof Bot; accent: string; pipeline: string[]; guardrail: string };
type BankTransaction = { id: string; txnDate: string; reference: string; narration: string; payer: string; amount: number; currency: string; account: string; status: MatchStatus; customer: string; invoice: string; confidence: number };

const agents: Agent[] = [
  { id: 'bi', name: 'BI Report Generator', purpose: 'Runs weekly BI queries, creates executive insights, and prepares recap blocks with chart links.', mode: 'Headless', model: 'claude-sonnet-4-6', mcp: ['supabase', 'slack'], schedule: 'Monday 07:00 UTC', status: 'Scheduled', icon: BarChart3, accent: 'gold', pipeline: ['Fetch active BI queries', 'Validate result sets', 'Compute weekly deltas', 'Compose recap', 'Log run'], guardrail: 'Never invent metrics. Failed queries are skipped and logged.' },
  { id: 'tax', name: 'Tax Prep Assistant', purpose: 'Categorizes transaction activity and flags deductible items for review.', mode: 'Interactive', model: 'claude-sonnet-4-6', mcp: ['stripe', 'brex', 'quickbooks'], schedule: 'On demand', status: 'Needs Connection', icon: FileSpreadsheet, accent: 'teal', pipeline: ['Confirm scope', 'Pull activity', 'Deduplicate records', 'Categorize expenses', 'Summarize review items'], guardrail: 'Low confidence items require confirmation.' },
  { id: 'canny', name: 'Canny Feedback Clusterer', purpose: 'Clusters feedback into themes and prepares ticket updates for high-signal requests.', mode: 'Headless', model: 'claude-sonnet-4-6', mcp: ['canny', 'linear'], schedule: 'Every 6 hours', status: 'Demo Mode', icon: MessageSquareText, accent: 'pink', pipeline: ['Fetch feedback', 'Deduplicate', 'Cluster themes', 'Check existing tickets', 'Prepare updates'], guardrail: 'Read-only feedback. No more than 10 tickets per run.' },
  { id: 'productboard', name: 'Productboard Insight Miner', purpose: 'Mines customer insights and produces a weekly PM brief.', mode: 'Headless', model: 'claude-sonnet-4-6', mcp: ['productboard'], schedule: 'Monday 08:00 UTC', status: 'Demo Mode', icon: BrainCircuit, accent: 'violet', pipeline: ['Fetch insights', 'Group by feature', 'Score themes', 'Extract red flags', 'Publish brief'], guardrail: 'Every insight must trace to a source record.' },
  { id: 'plaid', name: 'Plaid Cashflow Analyst', purpose: 'Analyzes bank transactions, runway, recurring items, and customer paid amounts from daily statements.', mode: 'Interactive', model: 'claude-sonnet-4-6', mcp: ['plaid'], schedule: 'On demand or daily import', status: 'Ready', icon: WalletCards, accent: 'green', pipeline: ['Load statement', 'Normalize rows', 'Extract paid amounts', 'Match customer/invoice', 'Route exceptions'], guardrail: 'Every amount must trace to a bank row.' },
  { id: 'metabase', name: 'Metabase Question Builder', purpose: 'Turns natural language analytics requests into SQL, chart choices, and saved cards.', mode: 'Interactive', model: 'claude-sonnet-4-6', mcp: ['metabase'], schedule: 'On demand', status: 'Needs Connection', icon: BarChart3, accent: 'blue', pipeline: ['Clarify', 'Discover schema', 'Draft SQL', 'Pick chart', 'Save after approval'], guardrail: 'SELECT-only SQL and explicit approval before save.' },
  { id: 'mercury', name: 'Mercury Reconciler', purpose: 'Matches bank transactions to accounting invoices and flags mismatches.', mode: 'Headless', model: 'claude-sonnet-4-6', mcp: ['mercury', 'xero'], schedule: 'Daily 06:00 UTC', status: 'Paused', icon: RefreshCcw, accent: 'orange', pipeline: ['Fetch bank rows', 'Fetch invoices', 'Match', 'Classify', 'Report'], guardrail: 'Read-only reconciliation. Multi-match needs human review.' },
  { id: 'sheets', name: 'Airtable / Sheets Agent', purpose: 'Finds rows, updates fields, and generates formulas with read-before-write controls.', mode: 'Interactive', model: 'claude-sonnet-4-6', mcp: ['airtable', 'google-sheets'], schedule: 'On demand', status: 'Needs Connection', icon: Table2, accent: 'cyan', pipeline: ['Classify intent', 'Read current rows', 'Confirm', 'Execute', 'Audit'], guardrail: 'Bulk changes require confirmation.' },
  { id: 'analyst', name: 'Data Analyst', purpose: 'Loads, explores, visualizes, and answers questions from finance datasets.', mode: 'Interactive', model: 'claude-sonnet-4-6', mcp: ['amplitude'], schedule: 'On demand', status: 'Ready', icon: Activity, accent: 'indigo', pipeline: ['Load', 'Inspect', 'Clean', 'Analyze', 'Summarize'], guardrail: 'Always inspect data before computing.' }
];

const seedRows: BankTransaction[] = [
  { id: 'BNK-001', txnDate: '2026-06-13', reference: 'INV-256010013000498', narration: 'NEFT CREDIT TECOM MGMT FEES INV 498', payer: 'TECOM Group', amount: 460320, currency: 'AED', account: 'ENBD Main AED', status: 'Matched', customer: 'TECOM Group', invoice: '256010013000498', confidence: 98 },
  { id: 'BNK-002', txnDate: '2026-06-13', reference: 'PAY-LIMITLESS-BUND', narration: 'TRANSFER LIMITLESS LLC BUND WALL SETTLEMENT', payer: 'Limitless LLC', amount: 713664, currency: 'AED', account: 'ENBD Main AED', status: 'Probable Match', customer: 'Limitless LLC', invoice: 'PO-00000739', confidence: 84 },
  { id: 'BNK-003', txnDate: '2026-06-13', reference: 'SSA-COACHING', narration: 'SUPER SPORTS ACADEMY PART PAYMENT', payer: 'Super Sports Academy', amount: 38568.85, currency: 'AED', account: 'Mashreq Collections', status: 'Matched', customer: 'Super Sports Academy', invoice: '22814', confidence: 93 },
  { id: 'BNK-004', txnDate: '2026-06-13', reference: 'UNALLOC-8842', narration: 'CREDIT CUSTOMER PAYMENT NO INVOICE REF', payer: 'Unknown Payer', amount: 125000, currency: 'AED', account: 'ENBD Main AED', status: 'Review Required', customer: 'Review required', invoice: '-', confidence: 42 },
  { id: 'BNK-005', txnDate: '2026-06-13', reference: 'MEYDAN-15006', narration: 'MEYDAN GROUP SETTLEMENT Q1 2023', payer: 'Meydan Group', amount: 600000, currency: 'AED', account: 'ENBD Main AED', status: 'Duplicate', customer: 'Meydan Group', invoice: '15006', confidence: 71 }
];

function money(value: number) { return new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED', maximumFractionDigits: 0 }).format(value); }
function tone(status: AgentStatus | MatchStatus) { return status === 'Ready' || status === 'Matched' ? 'good' : status === 'Scheduled' || status === 'Probable Match' ? 'info' : status === 'Needs Connection' || status === 'Review Required' || status === 'Duplicate' ? 'warn' : 'muted'; }
function score(row: Partial<BankTransaction>): BankTransaction { const text = `${row.narration || ''} ${row.reference || ''}`.toLowerCase(); const amount = Number(row.amount || 0); let customer = row.payer || 'Unknown Payer', invoice = '-', confidence = 35, status: MatchStatus = amount > 0 ? 'Review Required' : 'Unmatched Credit'; if (text.includes('tecom') || text.includes('256010013000498')) { customer = 'TECOM Group'; invoice = '256010013000498'; confidence = 98; status = 'Matched'; } else if (text.includes('limitless') || text.includes('bund')) { customer = 'Limitless LLC'; invoice = 'PO-00000739'; confidence = 84; status = 'Probable Match'; } else if (text.includes('super sports') || text.includes('22814')) { customer = 'Super Sports Academy'; invoice = '22814'; confidence = 93; status = 'Matched'; } else if (text.includes('meydan')) { customer = 'Meydan Group'; invoice = '15006'; confidence = 71; status = 'Duplicate'; } return { id: row.id || `UPL-${Date.now()}`, txnDate: row.txnDate || new Date().toISOString().slice(0, 10), reference: row.reference || '-', narration: row.narration || '-', payer: row.payer || customer, amount, currency: row.currency || 'AED', account: row.account || 'Manual Upload', status, customer, invoice, confidence }; }

export function App() {
  const [page, setPage] = useState<Page>('overview'); const [activeAgent, setActiveAgent] = useState(agents[4]); const [rows, setRows] = useState(seedRows); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All'); const [audit, setAudit] = useState(['21st.dev-style finance command center loaded.', 'Daily bank statement matcher initialized in demo mode.']); const [messages, setMessages] = useState([{ role: 'agent', text: 'Demo runtime active. Connect backend credentials to run real managed agents.' }]); const [chat, setChat] = useState('');
  const paidToday = useMemo(() => rows.filter((r) => r.amount > 0 && ['Matched', 'Probable Match'].includes(r.status)).reduce((s, r) => s + r.amount, 0), [rows]); const reviewCount = rows.filter((r) => ['Review Required', 'Duplicate', 'Probable Match'].includes(r.status)).length; const matchRate = Math.round((rows.filter((r) => r.status === 'Matched').length / rows.length) * 100); const filtered = rows.filter((r) => `${r.reference} ${r.narration} ${r.customer} ${r.payer}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All' || r.status === status));
  function upload(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => { const lines = String(reader.result || '').split(/\r?\n/).filter(Boolean).slice(1, 26); const imported = lines.map((line, i) => { const c = line.split(',').map((x) => x.trim()); return score({ id: `UPL-${Date.now()}-${i}`, txnDate: c[0], reference: c[1], narration: c[2], payer: c[3], amount: Number(c[4]), currency: c[5], account: c[6] }); }); setRows((current) => [...imported, ...current]); setAudit((a) => [`Imported ${imported.length} rows from ${file.name}.`, ...a]); setPage('bank'); }; reader.readAsText(file); }
  function approve(id: string) { setRows((rs) => rs.map((r) => r.id === id ? { ...r, status: 'Matched', confidence: Math.max(r.confidence, 95) } : r)); setAudit((a) => [`Approved payment match for ${id}.`, ...a]); } function reject(id: string) { setRows((rs) => rs.map((r) => r.id === id ? { ...r, status: 'Review Required', customer: 'Review required', invoice: '-', confidence: 25 } : r)); setAudit((a) => [`Rejected match for ${id}; routed to review.`, ...a]); } function runAgent(agent: Agent) { setActiveAgent(agent); setPage('agents'); setAudit((a) => [`Demo run queued for ${agent.name}.`, ...a]); setMessages((m) => [...m, { role: 'agent', text: `${agent.name} is ready in demo mode. Live execution needs its MCP connections.` }]); } function send() { if (!chat.trim()) return; setMessages((m) => [...m, { role: 'user', text: chat }, { role: 'agent', text: `I can prepare this workflow. Connect ${activeAgent.mcp.join(', ')} and approve the tool action for live execution.` }]); setChat(''); }
  return <div className="app-shell"><aside className="sidebar"><button className="brand" onClick={() => setPage('overview')}><span>D</span><div><strong>DHCM</strong><small>Agent Command Center</small></div></button><nav>{[['overview', Gauge], ['agents', Bot], ['bank', Landmark], ['reconciliation', Workflow], ['bi', BarChart3], ['audit', ShieldCheck], ['settings', LockKeyhole]].map(([id, Icon]) => <button key={id as string} className={page === id ? 'active' : ''} onClick={() => setPage(id as Page)}><Icon size={18} />{String(id)}</button>)}</nav><div className="sidebar-card"><ShieldCheck size={18} /><strong>Approval-first</strong><p>Every write or match action is routed through review.</p></div></aside><main className="main"><header className="topbar"><div><span>Demo runtime · Vercel/Vite</span><h1>Finance Agent Command Center</h1></div><div className="top-actions"><span className="pill good"><Database size={14}/>Supabase active</span><span className="pill warn">MCP pending</span><label className="upload"><UploadCloud size={16}/>Upload CSV<input hidden type="file" accept=".csv,.txt" onChange={(e) => upload(e.target.files?.[0])}/></label></div></header>{page === 'overview' && <Overview paidToday={paidToday} reviewCount={reviewCount} matchRate={matchRate} runAgent={runAgent} setPage={setPage}/>} {page === 'agents' && <Agents activeAgent={activeAgent} setActiveAgent={setActiveAgent} runAgent={runAgent} messages={messages} chat={chat} setChat={setChat} send={send}/>} {page === 'bank' && <Bank rows={filtered} query={query} setQuery={setQuery} status={status} setStatus={setStatus} approve={approve} reject={reject} upload={upload}/>} {page === 'reconciliation' && <Reconciliation rows={rows}/>} {page === 'bi' && <BI runAgent={runAgent}/>} {page === 'audit' && <Audit audit={audit}/>} {page === 'settings' && <Settings/>}<Footer/></main></div>;
}

function Overview({ paidToday, reviewCount, matchRate, runAgent, setPage }: { paidToday: number; reviewCount: number; matchRate: number; runAgent: (a: Agent) => void; setPage: (p: Page) => void }) { return <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="page-grid"><section className="hero-panel"><div><span className="eyebrow">21st.dev-inspired agent workspace</span><h2>Command center for AR, bank statement matching, BI, and managed finance agents.</h2><p>The app now models the attached UI and logic: agent cards, MCP chips, run panels, approval queues, audit logs, and customer paid amount extraction.</p><div className="hero-actions"><button className="primary" onClick={() => setPage('agents')}>Open agent fleet <ArrowRight size={16}/></button><button className="secondary" onClick={() => setPage('bank')}>Review payments</button></div></div><div className="agent-orbit">{agents.slice(0,5).map((a) => <button key={a.id} onClick={() => runAgent(a)}><a.icon size={18}/>{a.name}</button>)}</div></section><div className="kpi-grid"><Metric label="Customer paid today" value={money(paidToday)} tone="good"/><Metric label="Match rate" value={`${matchRate}%`} tone="info"/><Metric label="Review queue" value={`${reviewCount}`} tone="warn"/><Metric label="Agent templates" value={`${agents.length}`} tone="gold"/></div><section className="panel wide"><div className="panel-head"><div><span className="eyebrow">Agent fleet</span><h3>Templates mapped to finance workflows</h3></div><Sparkles size={18}/></div><div className="agent-grid">{agents.map((a) => <AgentCard key={a.id} agent={a} onOpen={() => runAgent(a)}/>)}</div></section></motion.section>; }
function Metric({label,value,tone}:{label:string;value:string;tone:string}){return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong><em>Demo data</em></div>}
function AgentCard({agent,onOpen}:{agent:Agent;onOpen:()=>void}){return <button className="agent-card" onClick={onOpen}><div className={`agent-icon ${agent.accent}`}><agent.icon size={20}/></div><div><strong>{agent.name}</strong><p>{agent.purpose}</p><div className="chips">{agent.mcp.map((m)=><span key={m}>{m}</span>)}</div></div><span className={`pill ${tone(agent.status)}`}>{agent.status}</span></button>}
function Agents({activeAgent,setActiveAgent,runAgent,messages,chat,setChat,send}:{activeAgent:Agent;setActiveAgent:(a:Agent)=>void;runAgent:(a:Agent)=>void;messages:{role:string;text:string}[];chat:string;setChat:(v:string)=>void;send:()=>void}){return <section className="two-column"><div className="panel"><div className="panel-head"><div><span className="eyebrow">Agent catalog</span><h3>Managed-agent models</h3></div><Bot size={18}/></div><div className="agent-list">{agents.map((a)=><button key={a.id} className={activeAgent.id===a.id?'selected':''} onClick={()=>setActiveAgent(a)}><a.icon size={18}/><div><strong>{a.name}</strong><span>{a.mode} · {a.schedule}</span></div><span className={`pill ${tone(a.status)}`}>{a.status}</span></button>)}</div></div><div className="panel detail"><div className="detail-head"><div className={`agent-icon ${activeAgent.accent}`}><activeAgent.icon size={26}/></div><div><span className="eyebrow">{activeAgent.mode} · {activeAgent.model}</span><h2>{activeAgent.name}</h2><p>{activeAgent.purpose}</p></div></div><div className="chips">{activeAgent.mcp.map((m)=><span key={m}>{m}</span>)}</div><div className="tabs"><button>Chat / Run</button><button>Configuration</button><button>Logs</button><button>Permissions</button></div><div className="pipeline">{activeAgent.pipeline.map((s,i)=><div key={s}><span>{i+1}</span>{s}</div>)}</div><div className="guardrail"><ShieldCheck size={18}/><p>{activeAgent.guardrail}</p></div><div className="chat-box">{messages.map((m,i)=><div key={i} className={`bubble ${m.role}`}>{m.text}</div>)}</div><div className="chat-input"><input value={chat} onChange={(e)=>setChat(e.target.value)} onKeyDown={(e)=>e.key==='Enter'&&send()} placeholder={`Ask ${activeAgent.name}...`}/><button onClick={send}>Send</button><button className="secondary" onClick={()=>runAgent(activeAgent)}><Play size={15}/>Run</button></div></div></section>}
function Bank({rows,query,setQuery,status,setStatus,approve,reject,upload}:{rows:BankTransaction[];query:string;setQuery:(v:string)=>void;status:string;setStatus:(v:string)=>void;approve:(id:string)=>void;reject:(id:string)=>void;upload:(f?:File)=>void}){return <section className="panel wide"><div className="panel-head"><div><span className="eyebrow">Daily bank statement</span><h3>Customer paid amount extraction</h3></div><label className="upload small"><UploadCloud size={15}/>Upload<input hidden type="file" accept=".csv,.txt" onChange={(e)=>upload(e.target.files?.[0])}/></label></div><div className="filters"><div><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search reference, payer, customer..."/></div><div><Filter size={16}/><select value={status} onChange={(e)=>setStatus(e.target.value)}>{['All','Matched','Probable Match','Review Required','Unmatched Credit','Duplicate'].map((s)=><option key={s}>{s}</option>)}</select></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Narration</th><th>Payer</th><th>Amount</th><th>Status</th><th>Customer</th><th>Invoice</th><th>Confidence</th><th>Review</th></tr></thead><tbody>{rows.map((r)=><tr key={r.id}><td>{r.txnDate}</td><td>{r.reference}</td><td>{r.narration}</td><td>{r.payer}</td><td>{money(r.amount)}</td><td><span className={`pill ${tone(r.status)}`}>{r.status}</span></td><td>{r.customer}</td><td>{r.invoice}</td><td><div className="confidence"><span style={{width:`${r.confidence}%`}}/>{r.confidence}%</div></td><td><button className="icon" onClick={()=>approve(r.id)}><CheckCircle2 size={15}/></button><button className="icon danger" onClick={()=>reject(r.id)}><XCircle size={15}/></button></td></tr>)}</tbody></table></div><p className="hint">CSV format: txnDate, reference, narration, payer, amount, currency, account.</p></section>}
function Reconciliation({rows}:{rows:BankTransaction[]}){const groups=rows.reduce<Record<string,number>>((a,r)=>({...a,[r.status]:(a[r.status]||0)+r.amount}),{});return <section className="page-grid"><div className="panel wide"><div className="panel-head"><div><span className="eyebrow">Reconciliation</span><h3>Bank-to-invoice exception control</h3></div><Workflow size={18}/></div><div className="recon-grid">{Object.entries(groups).map(([s,a])=><div key={s}><span className={`pill ${tone(s as MatchStatus)}`}>{s}</span><strong>{money(a)}</strong><p>Amount by match classification.</p></div>)}</div></div></section>}
function BI({runAgent}:{runAgent:(a:Agent)=>void}){return <section className="panel wide"><div className="panel-head"><div><span className="eyebrow">BI Report Generator</span><h3>Weekly executive recap</h3></div><button onClick={()=>runAgent(agents[0])}><Play size={15}/>Run demo</button></div><div className="report-layout"><div><h4>Revenue</h4><p>Matched cash is visible from bank statement rows.</p></div><div><h4>Operations</h4><p>Review queue highlights missing invoice references.</p></div><div><h4>Risk</h4><p>Duplicates and ambiguous payers need human approval.</p></div></div></section>}
function Audit({audit}:{audit:string[]}){return <section className="panel wide"><div className="panel-head"><div><span className="eyebrow">Audit</span><h3>Control log</h3></div><Clock3 size={18}/></div><div className="timeline">{audit.map((a,i)=><div key={i}><span>{new Date().toISOString().slice(0,10)}</span><p>{a}</p></div>)}</div></section>}
function Settings(){return <section className="page-grid"><div className="panel wide"><div className="panel-head"><div><span className="eyebrow">Connections</span><h3>Live execution requirements</h3></div><AlertTriangle size={18}/></div><div className="settings-grid">{['Supabase','Anthropic agents','Slack','Plaid','Metabase','Google Sheets','Airtable','Productboard','Mercury','Xero'].map((x,i)=><div key={x}><strong>{x}</strong><span className={`pill ${i===0?'good':'warn'}`}>{i===0?'Project found':'Needs setup'}</span></div>)}</div></div></section>}
function Footer(){return <footer className="footer"><div><strong>DHCM Finance Agent Command Center</strong><span>Vite compatible · Supabase ready · Approval-first automation</span></div><div>{['Product','Operations','Security','Resources','Legal'].map((x)=><button key={x}>{x}</button>)}</div></footer>}
export default App;
